after_script:
  - git init
  - git config user.name "aiokr"
  - git config user.email "aiokr@foxmail.com"
  - git add .
  - git commit -m "Update hitokoto By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Coding
  - git push --force --quiet "https://aiokr:${CO_TOKEN}@${CO_REF}" master:master

branches:
  only:
    - master

env:
 global:
   # Github
   - GH_REF: git@github.com:aiokr/hitokoto.git
   # Coding
   - CO_REF: git@git.coding.net:StarkChen/hitokoto.git