after_script:
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - git config --global user.name "aiokr"
  - git config --global user.email "aiokr@foxmail.com"
  - git add .
  - git commit -m "Update hitokoto By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Coding
  - git push --force --quiet "https://aiokr:${CO_TOKEN}@${CO_REF}" master:master

branches:
  only:
    - master

env:
 global:
   # Github
   - GH_REF: github.com/aiokr/hitokoto
   # Coding
   - CO_REF: git.coding.net/StarkChen/hitokoto.git