after_script:
  - cd ./public
  - git init
  - git config user.name "aiokr"
  - git config user.email "aiokr@foxmail.com"
  - git add .
  - git commit -m "Update hitokoto By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master 
  # Coding Pages
  - git push --force --quiet "https://aiokr:${CO_TOKEN}@${CO_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --quiet "https://${CI_TOKEN}@${GH_REF}" master:master --tags
  # Coding Pages
  - git push --quiet "https://aiokr:${CO_TOKEN}@${CO_REF}" master:master --tags

branches:
  only:
    - master

env:
 global:
   # Github Pages
   - GH_REF: git@github.com:aiokr/hitokoto.git
   # Coding Pages
   - CO_REF: git@git.coding.net:StarkChen/hitokoto.git