after_script:
  - git clone https://github.com/aiokr/hitokoto .deploy_git
  - cd .deploy_git
  - git checkout master
  - git config --global user.name "aiokr"
  - git config --global user.email "aiokr@foxmail.com"
  - git add .
  - git commit -m "Update hitokoto By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Coding
  - git push --force --quiet https://aiokr:${token}@git.coding.net/StarkChen/hitokoto.git/